thread 'main' panicked at 'explicit panic', ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs:15:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at '`async fn` resumed after panicking', ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-panic.rs:14:16
