
running 4 tests
test it_fails ... testing123
FAILED
test it_panics - should panic ... ok
test it_works ... ok
test it_writes_to_stdio ... ok

failures:

---- it_fails stdout ----
about to fail
thread 'it_fails' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `4`', ui/test-attrs/test-panic-abort-nocapture.rs:33:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    it_fails

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

