// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> () {
    let mut _0: ();
    let mut _1: (&usize, &usize);
    let mut _2: &usize;
    let _3: usize;
    let mut _4: &mut std::ops::Range<usize>;
    let mut _5: &mut std::ops::Range<usize>;
    let mut _6: &mut std::ops::Range<usize>;
    let mut _7: std::ops::Range<usize>;
    let _8: &usize;
    let _9: &usize;
    let mut _10: bool;
    let mut _11: bool;
    let mut _12: usize;
    let mut _13: usize;
    let _15: !;
    let mut _16: std::option::Option<std::fmt::Arguments<'_>>;
    let _17: std::result::Result<usize, std::boxed::Box<dyn std::any::Any + std::marker::Send>>;
    let mut _18: bool;
    let mut _19: bool;
    let mut _20: &std::result::Result<usize, std::boxed::Box<dyn std::any::Any + std::marker::Send>>;
    let mut _21: !;
    let mut _22: &usize;
    scope 1 {
        debug left_val => _8;
        debug right_val => _9;
        let _14: core::panicking::AssertKind;
        scope 2 {
            debug kind => _14;
        }
    }
    scope 3 {
        debug r => _17;
    }

    bb0: {
        _7 = std::ops::Range::<usize> { start: const 0_usize, end: const _ };
        _6 = &mut _7;
        _5 = <std::ops::Range<usize> as Iterator>::by_ref(move _6) -> [return: bb1, unwind continue];
    }

    bb1: {
        _4 = _5;
        _3 = <&mut std::ops::Range<usize> as Iterator>::count(move _4) -> [return: bb2, unwind continue];
    }

    bb2: {
        _2 = &_3;
        _22 = const _;
        _1 = (move _2, _22);
        _8 = (_1.0: &usize);
        _9 = (_1.1: &usize);
        _12 = (*_8);
        _13 = (*_9);
        _11 = Eq(move _12, move _13);
        _10 = Not(move _11);
        switchInt(move _10) -> [0: bb4, otherwise: bb3];
    }

    bb3: {
        _14 = core::panicking::AssertKind::Eq;
        _16 = Option::<Arguments<'_>>::None;
        _15 = core::panicking::assert_failed::<usize, usize>(move _14, _8, _9, move _16) -> unwind continue;
    }

    bb4: {
        _17 = catch_unwind::<[closure@ui/iterators/iter-count-overflow-debug.rs:11:33: 11:35], usize>(const ZeroSized: [closure@ui/iterators/iter-count-overflow-debug.rs:11:33: 11:35]) -> [return: bb5, unwind continue];
    }

    bb5: {
        _20 = &_17;
        _19 = Result::<usize, Box<dyn Any + Send>>::is_err(move _20) -> [return: bb6, unwind: bb10];
    }

    bb6: {
        _18 = Not(move _19);
        switchInt(move _18) -> [0: bb8, otherwise: bb7];
    }

    bb7: {
        _21 = core::panicking::panic(const "assertion failed: r.is_err()") -> bb10;
    }

    bb8: {
        drop(_17) -> [return: bb9, unwind continue];
    }

    bb9: {
        return;
    }

    bb10 (cleanup): {
        drop(_17) -> [return: bb11, unwind terminate];
    }

    bb11 (cleanup): {
        resume;
    }
}

promoted[0] in main: &usize = {
    let mut _0: &usize;
    let mut _1: usize;

    bb0: {
        _1 = const _;
        _0 = &_1;
        return;
    }
}

fn main::{closure#0}(_1: [closure@ui/iterators/iter-count-overflow-debug.rs:11:33: 11:35]) -> usize {
    let mut _0: usize;
    let mut _2: &mut std::ops::RangeInclusive<usize>;
    let mut _3: &mut std::ops::RangeInclusive<usize>;
    let mut _4: &mut std::ops::RangeInclusive<usize>;
    let mut _5: std::ops::RangeInclusive<usize>;

    bb0: {
        _5 = RangeInclusive::<usize>::new(const 0_usize, const _) -> [return: bb1, unwind continue];
    }

    bb1: {
        _4 = &mut _5;
        _3 = <RangeInclusive<usize> as Iterator>::by_ref(move _4) -> [return: bb2, unwind continue];
    }

    bb2: {
        _2 = _3;
        _0 = <&mut RangeInclusive<usize> as Iterator>::count(move _2) -> [return: bb3, unwind continue];
    }

    bb3: {
        return;
    }
}
